FROM apache/nifi

COPY --chown=nifi:nifi ./ojdbc8-21.5.0.0.jar /opt/nifi/nifi-current/lib/ojdbc8-21.5.0.0.jar

ENV SINGLE_USER_CREDENTIALS_USERNAME=admin
ENV SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
