SELECT 
   (SELECT 
      ROUND (AVG (BYTES) / 1024 / 1024, 2) 
   FROM 
      GV$LOG) AS "Redo size (MB)", 
   ROUND ( (20 / AVERAGE_PERIOD) * (SELECT AVG (BYTES) FROM V$LOG) / 1024 / 1024, 2) AS "Recommended Size (MB)" 
FROM 
   (SELECT AVG ( (NEXT_TIME - FIRST_TIME) * 24 * 60) AS    
   AVERAGE_PERIOD 
   FROM 
   GV$ARCHIVED_LOG 
   WHERE 
   FIRST_TIME > SYSDATE - 1
   AND 
   TO_CHAR (FIRST_TIME, 'HH24:MI') BETWEEN '00:00' AND '23:59');
