SELECT
    O.OBJECT_NAME,
    S.SID,
    S.SERIAL#,
    P.SPID,
    S.PROGRAM,
    SQ.SQL_FULLTEXT,
    S.LOGON_TIME
FROM
    GV$LOCKED_OBJECT L,
    DBA_OBJECTS O,
    GV$SESSION S,
    GV$PROCESS P,
    GV$SQL SQ
WHERE
    L.OBJECT_ID = O.OBJECT_ID
    AND L.SESSION_ID = S.SID
    AND S.PADDR = P.ADDR
    AND S.SQL_ADDRESS = SQ.ADDRESS
    AND O.OBJECT_NAME LIKE '%&TABLE_NAME%'
    ;
