-- remote database
create directory dir2 as '+DG_DATA/NFEDEV/DATAFILE';
-- local database
create directory dir1 as '+NFEDEV_DATA/NFEDEV/DATAFILE';
 
create public database link onfedev connect to system identified by ORACLE using 'ONFEDEV';
  

CREATE TABLE CONTROL_MIGRATION (ID_MIGRATION NUMBER(2), S_DIRECTORY VARCHAR2(50), D_DIRECTORY VARCHAR2(50), S_DATABASE_LINK VARCHAR2(30), NR_LOCK_FILES NUMBER(1));
INSERT INTO CONTROL_MIGRATION VALUES(1,'DIR1','DIR2','ONFEDEV',3);
CREATE TABLE CONTROL_MIGRATION_FILE (ID_MIGRATION NUMBER(2), S_FILE_NAME VARCHAR2(100), D_FILE_NAME VARCHAR2(100), FL_STAT NUMBER(1), FL_LOCK NUMBER(4));
CREATE TABLE CONTROL_MIGRATION_LOG (ID_MIGRATION NUMBER(2), DT_START DATE, DT_END DATE, D_FILE_NAME VARCHAR2(100),DESC_MSG VARCHAR2(255));
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'ts_cte.269.952184621','ts_cte.269',0,0);
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'TS_DAT_01.259.891670945','TS_DAT_01.259',0,0);
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'TS_DAT_01.260.891670947','TS_DAT_01.260',0,0);
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'TS_DAT_01.261.891670949','TS_DAT_01.261',0,0);
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'TS_IDX_01.258.891670941','TS_IDX_01.258',0,0);
INSERT INTO CONTROL_MIGRATION_FILE VALUES (1,'USERS.263.1022422029','USERS.263',0,0);



DECLARE
vID_MIGRATION NUMBER(2) :='';
vS_DIRECTORY VARCHAR2(50) :='';
vD_DIRECOTRY VARCHAR2(50) :='';
vS_DATABASE_LINK VARCHAR2(30) :='';
vFL_LOCK NUMBER(4) :='';
BEGIN

	--Generate lock value
	SELECT TRUNC(DBMS_RANDOM.value(1,10000)) INTO vFL_LOCK FROM DUAL;
	--GET CONFIG
	SELECT ID_MIGRATION, S_DIRECTORY,D_DIRECTORY, S_DATABASE_LINK  INTO vID_MIGRATION,vS_DIRECTORY,vD_DIRECOTRY,vS_DATABASE_LINK FROM CONTROL_MIGRATION where ID_MIGRATION = (SELECT MAX(ID_MIGRATION) FROM CONTROL_MIGRATION);

	FOR C_M_LOCK_DATA IN (SELECT S_FILE_NAME S_FILE_NAME, D_FILE_NAME D_FILE_NAME FROM CONTROL_MIGRATION_FILE WHERE ID_MIGRATION = vID_MIGRATION AND FL_STAT=0 AND FL_LOCK = 0 AND ROWNUM <2)
		LOOP

			UPDATE CONTROL_MIGRATION_FILE SET FL_LOCK=vFL_LOCK WHERE ID_MIGRATION=vID_MIGRATION AND D_FILE_NAME=C_M_LOCK_DATA.D_FILE_NAME AND FL_STAT=0;
			COMMIT;	
			
		END LOOP;

	FOR C_M_FILE IN (SELECT S_FILE_NAME S_FILE_NAME, D_FILE_NAME D_FILE_NAME FROM CONTROL_MIGRATION_FILE WHERE ID_MIGRATION = vID_MIGRATION AND FL_STAT=0 AND FL_LOCK=vFL_LOCK)
		LOOP

			UPDATE CONTROL_MIGRATION_FILE SET FL_STAT=9 WHERE ID_MIGRATION=vID_MIGRATION AND D_FILE_NAME=C_M_FILE.D_FILE_NAME;
			COMMIT;
			INSERT INTO CONTROL_MIGRATION_LOG VALUES(vID_MIGRATION,SYSDATE,NULL,C_M_FILE.D_FILE_NAME);
			COMMIT;

			DBMS_FILE_TRANSFER.get_file(
   			source_directory_object      => vS_DIRECTORY,
   			source_file_name             => C_M_FILE.S_FILE_NAME,
   			source_database              => vS_DATABASE_LINK,
   			destination_directory_object => vD_DIRECOTRY,
   			destination_file_name        => C_M_FILE.D_FILE_NAME);

			UPDATE CONTROL_MIGRATION_LOG SET DT_END=SYSDATE WHERE ID_MIGRATION = vID_MIGRATION AND D_FILE_NAME=C_M_FILE.D_FILE_NAME;
			COMMIT;
			UPDATE CONTROL_MIGRATION_FILE SET FL_STAT=1,FL_LOCK=0 WHERE ID_MIGRATION=vID_MIGRATION AND D_FILE_NAME=C_M_FILE.D_FILE_NAME AND  FL_LOCK=vFL_LOCK;
			COMMIT;

		END LOOP;


END;
/


/*
column S_FILE_NAME format a30
column D_FILE_NAME format a30
select * from CONTROL_MIGRATION_FILE;

update CONTROL_MIGRATION_FILE set FL_STAT=0,FL_LOCK=0;

--Check eleapsed
alter session set nls_date_format='dd/mm/yyyy hh24:mi:ss';
select  cml.*, trunc(mod(mod(SYSDATE - DT_START,1)*24,1)*60) as mins from CONTROL_MIGRATION_LOG cml where DT_END IS NULL;

--Check finalized
alter session set nls_date_format='dd/mm/yyyy hh24:mi:ss';
column D_FILE_NAME format a30
select  cml.*, trunc(mod(mod(DT_END - DT_START,1)*24,1)*60) as mins from CONTROL_MIGRATION_LOG cml;

*/
