CREATE SCRIPT ARCHIVE_LOG
{

        ALLOCATE CHANNEL t1 DEVICE TYPE SBT_TAPE PARMS 'SBT_LIBRARY=/opt/veeam/VeeamPluginforOracleRMAN/libOracleRMANPlugin.so' FORMAT 'dedf2dda-c24a-4ee2-8b2a-0ca1d21ff635/RMAN_ARCH_%I_%d_%U_%T.vab';
        BACKUP ARCHIVELOG ALL FORMAT 'RMAN_ARCH_%I_%d_%U_%T.vab' DELETE ALL INPUT SKIP INACCESSIBLE KEEP UNTIL TIME 'SYSDATE+7';
        RELEASE CHANNEL t1;

}
