CREATE SCRIPT CROSSCHECK_BACKUP
{
    ALLOCATE CHANNEL t1 DEVICE TYPE SBT_TAPE PARMS 'SBT_LIBRARY=/opt/veeam/VeeamPluginforOracleRMAN/libOracleRMANPlugin.so';
		CROSSCHECK BACKUP;
    DELETE NOPROMPT OBSOLETE;
		DELETE NOPROMPT EXPIRED;
}
